basic_spam_rule = {
    "MarkFlagged": False,
    "ShouldTransferMessage": True,
    "MailboxURL": "Junk",
    "AllCriteriaMustBeSatisfied": False,
    "AutoResponseType": 2,
    "CopyToMailboxURL": "Junk",
    "Criteria": [
    ],
    "Deletes": False,
    "HighlightTextUsingColor": False,
    "MarkRead": True,
    "NotifyUser": False,
    "ResponseMessage": "[AUTOMATED MESSAGE]\n\nHello,\n\nPlease remove this email from your list.\n\n\nThank you.",
    "RuleId": "",
    "RuleName": "Recruiter spam",
    "SendNotification": False,
    "ShouldCopyMessage": False,
    "TimeStamp": 657874934,
}
